# Open file:// links with #<line> fragments directly in Neovim.
protocol file
fragment_matches [0-9]+
action launch --cwd=current -- $EDITOR +$FRAGMENT -- $FILE_PATH

# Open plain text files in Neovim.
protocol file
mime text/*
action launch --cwd=current -- $EDITOR -- $FILE_PATH
