# Overall format - customize the order of modules
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$kubernetes\
$terraform\
$docker_context\
$helm\
$aws\
$gcloud\
$azure\
$python\
$nodejs\
$golang\
$rust\
$cmd_duration\
$jobs\
$status\
$line_break\
$character
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
format = '([\[$all_status$ahead_behind\]]($style) )'

[aws]
symbol = "aws "

[azure]
symbol = "az "

[buf]
symbol = "buf "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cpp]
symbol = "C++ "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[container]
symbol = "container "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[docker_context]
disabled = false
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '


[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
symbol = "git "

[gleam]
symbol = "gleam "

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[haskell]
symbol = "haskell "

[helm]
symbol = "helm "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[kubernetes]
disabled = false
format = 'on [⛵ $context(\($namespace\))]($style) '
style = "cyan bold"
detect_env_vars = ["KUBECONFIG"]


[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nats]
symbol = "nats "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
Bluefin = "blfn "
CachyOS = "cach "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
Nobara = "nbra "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Uos = "uos "
Void = "void "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pixi]
symbol = "pixi "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[quarto]
symbol = "quarto "

[raku]
symbol = "raku "

[rlang]
symbol = "r "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[typst]
symbol = "typst "

[terraform]
disabled = false
format = "via [tf:$workspace]($style) "
style = "bold purple"
detect_extensions = ["tf", "tfvars"]
detect_files = [
  ".terraform.lock.hcl",
  "terraform.tfstate",
  "terraform.tfstate.backup",
]
detect_folders = [".terraform"]

[zig]
symbol = "zig "

[cmd_duration]
disabled = false
min_time = 2_000
format = "took [$duration]($style) "
style = "yellow bold"

[line_break]
disabled = false
